# Simple workflow for deploying static content to GitHub Pages
name: Revisar Proyecto Web

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

jobs:
  primer_job:
    runs-on: ubuntu-latest
    steps:
      - name : Revisar archivos antes
        run: ls

