name: publicar contenido en github pages

on: 
  push:
    branches: ["master"]

permissions: 
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages 
  cancel-in-progress: false

jobs:
  on-deploy: 
    enviroment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: instalar pages
        uses: actions/configure-pages@v5
      - name: cargar pagina
        uses: actions/upload-pages-articfact@v3
        with: 
          path: '.'
      - name: Desplegar pagina
        id: deployment
        uses: actions/deploy-pages@v4
