name: Integracion a DockerHub

on: 
  push:
    branches: ["master"]


jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4
      - name: Login a DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{secrects.DOCKERHUB_USERNAME}}
          password: ${{secrects.DOCKERHUB_TOKEN}}
      - name: Build Docker Image
        run: |
          docker build -t pagina-prueba .
      - name: push Docker File to Docker hub
        run: docker tag pagina-prueba ${{secrets.DOCKERHUB_USERNAME}}/pagina-prueba:latest
             docker push ${{secrets.DOCKERHUB_USERNAME}}/pagina-prueba:latest